### ISSUE TITLE
don"t have file laptop

### ISSUE THREAD

**Issue by ghost** [storopoli/flakes#46]
i have clone 
**git clone --recursive https://github.com/storopoli/flakes.git /mnt/etc/nixos/flakes**

but i don't have this file
**/mnt/etc/nixos/flakes/hosts/laptop/wayland/default.nix**
![image](https://github.com/storopoli/flakes/assets/151699722/299d311e-67ba-4675-a710-37e6a6e29e3a)

Can i install it after installing nixos minial ?
Sorry if I bother you. Looking forward to your and everyone's help.

**Comment by storopoli** [comment]
I've updated the README. Can you please check?

**Comment by ghost** [comment]
> I've updated the README. Can you please check?

Oh, thank you.
