### ISSUE TITLE
Error flake does not provide attribute

### ISSUE THREAD

**Issue by ghost** [storopoli/flakes#47]
![image](https://github.com/storopoli/flakes/assets/151699722/e15fe31a-225f-4806-add2-927cfc2764fa)

Hello, It's me again. i quite confused in this step: **7. Migrate all the custom hardware-configuration.nix from /mnt/etc/nixos into /mnt/etc/nixos/flakes/linux/system.nix and /mnt/etc/nixos/flakes/linux/filesystem.nix**

Following this step, I did `cp /mnt/etc/nixos/hardware-configuration.nix to /mnt/etc/nixos/flakes/linux/system.nix and /mnt/etc/nixos/flakes/linux/filesystem.nix`

in the photo at /mnt/etc/nixos there is 
![image](https://github.com/storopoli/flakes/assets/151699722/d3a3b27b-296d-4870-8397-8d264b0275e8)

After using` nixos-install --no-root-passwd --flake .#laptop` ( After the error, I tried `.#linux `  But it's still like that ).

Looking forward to your help,

**Comment by storopoli** [comment]
When I say migrate I mean "carefully go over the contents of the target file and add stuff from the original file", not a blind `cp original target`.


> I tried `.#linux`

Theres is no host named `linux` so this is expected to fail.

**Comment by ghost** [comment]
Ok. I will try again.

**Comment by storopoli** [comment]
Seems that it was fixed. I'll close this. Feel free to reach out if you need additional help.
